version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tigger_sms_proxy_app
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - mysql
        ports:
            - "8000:8000"
        networks:
            - tigger_net
        volumes:
            - .:/var/www

    mysql:
        image: mysql:8.3
        container_name: tigger_sms_proxy_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret123
            MYSQL_DATABASE: tigger_sms_proxy
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - tigger_net

networks:
    tigger_net:

volumes:
    db_data:
